export type PortfolioImageCategory =
  | "floral"
  | "bolo"
  | "mesa-doces"
  | "detalhes"
  | "ambiente";

export type PortfolioImageInventoryItem = {
  id: string;
  src: string;
  alt: string;
  category: PortfolioImageCategory;
  width: number;
  height: number;
  sourceOriginal: string;
  featuredOnHome?: true;
  heroImage?: true;
};

const imagePath = "/images/casamento-jessica-renan";

export const casamentoJessicaRenanImages = [
  {
    id: "mesa-doces-estante-floral-01",
    src: `${imagePath}/mesa-doces-estante-floral-01.webp`,
    alt: "Estante de madeira com doces e rosas vermelhas na decoração do casamento",
    category: "mesa-doces",
    width: 1066,
    height: 1600,
    sourceOriginal: "armario-doces.jpeg",
  },
  {
    id: "bolo-branco-rosas-01",
    src: `${imagePath}/bolo-branco-rosas-01.webp`,
    alt: "Detalhe do bolo branco decorado com rosas vermelhas e folhagens",
    category: "bolo",
    width: 1066,
    height: 1600,
    sourceOriginal: "bolo2.jpeg",
  },
  {
    id: "bolo-rosas-fundo-floral-02",
    src: `${imagePath}/bolo-rosas-fundo-floral-02.webp`,
    alt: "Bolo de casamento com rosas em frente ao painel floral colorido",
    category: "bolo",
    width: 1600,
    height: 1066,
    sourceOriginal: "bolo3.jpeg",
  },
  {
    id: "bolo-branco-rosas-03",
    src: `${imagePath}/bolo-branco-rosas-03.webp`,
    alt: "Bolo branco de dois andares adornado com rosas vermelhas",
    category: "bolo",
    width: 1066,
    height: 1600,
    sourceOriginal: "bolo.jpeg",
  },
  {
    id: "floral-painel-colorido-01",
    src: `${imagePath}/floral-painel-colorido-01.webp`,
    alt: "Painel floral volumoso com flores em tons de vinho, coral e rosa",
    category: "floral",
    width: 1600,
    height: 1066,
    sourceOriginal: "flores2.jpeg",
    featuredOnHome: true,
  },
  {
    id: "floral-arranjo-bistro-02",
    src: `${imagePath}/floral-arranjo-bistro-02.webp`,
    alt: "Arranjo de flores coloridas sobre mesa bistrô iluminada pelo sol",
    category: "floral",
    width: 1600,
    height: 1066,
    sourceOriginal: "flores-bistro.jpeg",
  },
  {
    id: "floral-rosas-vermelhas-03",
    src: `${imagePath}/floral-rosas-vermelhas-03.webp`,
    alt: "Close de rosas vermelhas usadas na decoração do casamento",
    category: "floral",
    width: 1600,
    height: 1066,
    sourceOriginal: "flores.jpeg",
  },
  {
    id: "ambiente-mesa-bolo-floral-01",
    src: `${imagePath}/ambiente-mesa-bolo-floral-01.webp`,
    alt: "Mesa do bolo cercada por flores, doces e folhagens em cores quentes",
    category: "ambiente",
    width: 1600,
    height: 1066,
    sourceOriginal: "mesa-bolo-decoracao2.jpeg",
    featuredOnHome: true,
  },
  {
    id: "ambiente-jardim-orquideas-02",
    src: `${imagePath}/ambiente-jardim-orquideas-02.webp`,
    alt: "Jardim com orquídeas rosas compondo a decoração da mesa do bolo",
    category: "ambiente",
    width: 1066,
    height: 1600,
    sourceOriginal: "mesa-bolo-decoracao3.jpeg",
  },
  {
    id: "bolo-rosas-painel-04",
    src: `${imagePath}/bolo-rosas-painel-04.webp`,
    alt: "Bolo de três andares diante de painel de flores vermelhas e laranjas",
    category: "bolo",
    width: 1600,
    height: 1066,
    sourceOriginal: "mesa-bolo-decoracao4.jpeg",
  },
  {
    id: "bolo-rosas-orquideas-05",
    src: `${imagePath}/bolo-rosas-orquideas-05.webp`,
    alt: "Bolo decorado com rosas e orquídeas em fundo floral",
    category: "bolo",
    width: 1066,
    height: 1600,
    sourceOriginal: "mesa-bolo-decoracao5.jpeg",
    featuredOnHome: true,
  },
  {
    id: "ambiente-mesa-bolo-floral-03",
    src: `${imagePath}/ambiente-mesa-bolo-floral-03.webp`,
    alt: "Composição completa da mesa do bolo com doces, flores e folhagens",
    category: "ambiente",
    width: 1600,
    height: 1066,
    sourceOriginal: "mesa-bolo-decoracao.jpeg",
  },
  {
    id: "mesa-doces-forminhas-coloridas-02",
    src: `${imagePath}/mesa-doces-forminhas-coloridas-02.webp`,
    alt: "Doces em forminhas florais nas cores da decoração do casamento",
    category: "mesa-doces",
    width: 1600,
    height: 1066,
    sourceOriginal: "mesa-doces2.jpeg",
  },
  {
    id: "mesa-doces-charutos-03",
    src: `${imagePath}/mesa-doces-charutos-03.webp`,
    alt: "Charutos decorativos entre rosas e doces na mesa de casamento",
    category: "mesa-doces",
    width: 1600,
    height: 1066,
    sourceOriginal: "mesa-doces3.jpeg",
    featuredOnHome: true,
  },
  {
    id: "mesa-doces-flores-04",
    src: `${imagePath}/mesa-doces-flores-04.webp`,
    alt: "Doces e rosas vermelhas em composição sobre a mesa de doces",
    category: "mesa-doces",
    width: 1600,
    height: 1066,
    sourceOriginal: "mesa-doces4-flores.jpeg",
  },
  {
    id: "detalhes-velas-e-doces-01",
    src: `${imagePath}/detalhes-velas-e-doces-01.webp`,
    alt: "Vela dourada acesa entre doces e flores da decoração",
    category: "detalhes",
    width: 1066,
    height: 1600,
    sourceOriginal: "mesa-doces5-velas.jpeg",
  },
  {
    id: "mesa-doces-forminhas-florais-05",
    src: `${imagePath}/mesa-doces-forminhas-florais-05.webp`,
    alt: "Doces em forminhas verdes e brancas junto a rosas vermelhas",
    category: "mesa-doces",
    width: 1066,
    height: 1600,
    sourceOriginal: "mesa-doces.jpeg",
  },
  {
    id: "detalhes-velas-douradas-02",
    src: `${imagePath}/detalhes-velas-douradas-02.webp`,
    alt: "Duas velas em castiçais dourados iluminando a decoração",
    category: "detalhes",
    width: 1600,
    height: 1066,
    sourceOriginal: "velas.jpeg",
  },
  {
    id: "mesa-doces-doces-laranjas-06",
    src: `${imagePath}/mesa-doces-doces-laranjas-06.webp`,
    alt: "Doces laranja em forminhas florais sobre a mesa decorada",
    category: "mesa-doces",
    width: 1066,
    height: 1600,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (11).jpeg",
  },
  {
    id: "detalhes-velas-e-folhagens-03",
    src: `${imagePath}/detalhes-velas-e-folhagens-03.webp`,
    alt: "Vela dourada e folhagens entre flores laranjas da decoração",
    category: "detalhes",
    width: 1066,
    height: 1600,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (12).jpeg",
  },
  {
    id: "floral-rosas-gigantes-04",
    src: `${imagePath}/floral-rosas-gigantes-04.webp`,
    alt: "Rosas gigantes decorativas em tom rosa na decoração do casamento",
    category: "floral",
    width: 1600,
    height: 1066,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (13).jpeg",
  },
  {
    id: "detalhes-flores-laranjas-04",
    src: `${imagePath}/detalhes-flores-laranjas-04.webp`,
    alt: "Flores laranjas e folhagens em detalhe na mesa decorada",
    category: "detalhes",
    width: 1066,
    height: 1600,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (14).jpeg",
  },
  {
    id: "detalhes-vaso-e-velas-05",
    src: `${imagePath}/detalhes-vaso-e-velas-05.webp`,
    alt: "Vaso em tom cobre com velas e flores da decoração",
    category: "detalhes",
    width: 1066,
    height: 1600,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (15).jpeg",
  },
  {
    id: "detalhes-retrato-e-velas-06",
    src: `${imagePath}/detalhes-retrato-e-velas-06.webp`,
    alt: "Retrato do casal acompanhado de flores e vela dourada",
    category: "detalhes",
    width: 1066,
    height: 1600,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (16).jpeg",
  },
  {
    id: "detalhes-flores-e-retrato-07",
    src: `${imagePath}/detalhes-flores-e-retrato-07.webp`,
    alt: "Arranjo de rosas ao lado de retrato do casal na decoração",
    category: "detalhes",
    width: 1066,
    height: 1600,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (17).jpeg",
  },
  {
    id: "detalhes-arranjo-e-moldura-08",
    src: `${imagePath}/detalhes-arranjo-e-moldura-08.webp`,
    alt: "Arranjo de rosas e moldura decorativa sobre a mesa",
    category: "detalhes",
    width: 1066,
    height: 1600,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (18).jpeg",
  },
  {
    id: "detalhes-retrato-e-presentes-09",
    src: `${imagePath}/detalhes-retrato-e-presentes-09.webp`,
    alt: "Retrato do casal com flores e presentes na mesa decorada",
    category: "detalhes",
    width: 1600,
    height: 1066,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (19).jpeg",
  },
  {
    id: "detalhes-retrato-vaso-floral-10",
    src: `${imagePath}/detalhes-retrato-vaso-floral-10.webp`,
    alt: "Retrato do casal, vaso de rosas e vela em composição intimista",
    category: "detalhes",
    width: 1066,
    height: 1600,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (20).jpeg",
  },
  {
    id: "ambiente-mesa-bolo-luzes-04",
    src: `${imagePath}/ambiente-mesa-bolo-luzes-04.webp`,
    alt: "Mesa do bolo completa diante de painel de folhagens, com orquídeas e doces",
    category: "ambiente",
    width: 1600,
    height: 1066,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (21).jpeg",
    featuredOnHome: true,
    heroImage: true,
  },
  {
    id: "ambiente-mesa-bolo-luzes-05",
    src: `${imagePath}/ambiente-mesa-bolo-luzes-05.webp`,
    alt: "Vista ampla da mesa do bolo iluminada por cordões de luz",
    category: "ambiente",
    width: 1600,
    height: 1066,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (22).jpeg",
  },
  {
    id: "ambiente-mesa-bolo-luzes-06",
    src: `${imagePath}/ambiente-mesa-bolo-luzes-06.webp`,
    alt: "Mesa do bolo com flores, doces e luzes em ambiente noturno",
    category: "ambiente",
    width: 1600,
    height: 1066,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (23).jpeg",
  },
  {
    id: "detalhes-bar-e-doces-11",
    src: `${imagePath}/detalhes-bar-e-doces-11.webp`,
    alt: "Taças, bebidas e doces compondo o bar da celebração",
    category: "detalhes",
    width: 1600,
    height: 1066,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (24).jpeg",
    featuredOnHome: true,
  },
  {
    id: "detalhes-drinks-12",
    src: `${imagePath}/detalhes-drinks-12.webp`,
    alt: "Taças e garrafas organizadas como detalhe da recepção",
    category: "detalhes",
    width: 1600,
    height: 1066,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (25).jpeg",
  },
  {
    id: "detalhes-bebidas-13",
    src: `${imagePath}/detalhes-bebidas-13.webp`,
    alt: "Garrafas e elementos de bar em mesa de madeira",
    category: "detalhes",
    width: 1600,
    height: 1066,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (26).jpeg",
  },
  {
    id: "detalhes-bar-roleta-14",
    src: `${imagePath}/detalhes-bar-roleta-14.webp`,
    alt: "Roleta de brincadeira de shots ao lado de garrafas no bar",
    category: "detalhes",
    width: 1066,
    height: 1600,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55 (27).jpeg",
  },
  {
    id: "ambiente-casal-07",
    src: `${imagePath}/ambiente-casal-07.webp`,
    alt: "Casal de noivos diante da mesa do bolo decorada com flores",
    category: "ambiente",
    width: 1066,
    height: 1600,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.16.18.jpeg",
    featuredOnHome: true,
  },
  {
    id: "floral-rosas-vermelhas-05",
    src: `${imagePath}/floral-rosas-vermelhas-05.webp`,
    alt: "Buquê de rosas vermelhas e rosas com folhagens ao fundo",
    category: "floral",
    width: 1066,
    height: 1600,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.13.55.jpeg",
  },
  {
    id: "ambiente-mesa-a-luz-de-velas-08",
    src: `${imagePath}/ambiente-mesa-a-luz-de-velas-08.webp`,
    alt: "Mesa da recepção iluminada por velas em ambiente noturno",
    category: "ambiente",
    width: 1600,
    height: 1066,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.20.47 (1).jpeg",
  },
  {
    id: "ambiente-mesa-a-luz-de-velas-09",
    src: `${imagePath}/ambiente-mesa-a-luz-de-velas-09.webp`,
    alt: "Mesa posta à luz de velas com arranjo de flores vermelhas ao fundo",
    category: "ambiente",
    width: 1600,
    height: 1066,
    sourceOriginal: "WhatsApp Image 2026-09-14 at 18.20.47.jpeg",
    featuredOnHome: true,
  },
] as const satisfies readonly PortfolioImageInventoryItem[];

export const homeHighlightImageIds = [
  "ambiente-mesa-bolo-luzes-04",
  "ambiente-mesa-bolo-floral-01",
  "bolo-rosas-orquideas-05",
  "floral-painel-colorido-01",
  "mesa-doces-charutos-03",
  "detalhes-bar-e-doces-11",
  "ambiente-casal-07",
  "ambiente-mesa-a-luz-de-velas-09",
] as const;

export const heroImageId = "ambiente-mesa-bolo-luzes-04";
